version: "3"
services:
  darts-matcher-legacy-web:
    restart: always
    image: darts-matcher-legacy-web
    container_name: darts-matcher-legacy-web
    build:
      context: .
      args:
        - PROFILE=dev # Accepts dev, prod-pi
    ports:
      - "4200:80"
